worker_processes auto;

events { 
  worker_connections 1024; 
}

http {

  # Define zona de rate limit por IP
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

  # Define que o status retornado ao exceder limite será 429
  limit_req_status 429;

  # Limita tamanho máximo do corpo da requisição para 1MB
  client_max_body_size 1M;

  # Define formato personalizado de log
  log_format log_api 'IP: $remote_addr | Metodo: $request_method | Rota: $uri | Status: $status | Tempo Upstream: ${upstream_response_time}s';

  #saída do log
  access_log /dev/stdout log_api;

  # Define configuração e área de cache para proxy
  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=api_cache:10m max_size=1g inactive=10m use_temp_path=off;

  # Ativa gzip
  gzip on;

  # Define tipos MIME que serão comprimidos
  gzip_types application/json text/plain;
    
  upstream user_service {
    server api-user:8080;
  }

  upstream passagem_service {
    server api-passagem:8080;
  }

  upstream voo_service {
    server api-voo:8080;
  }

  server {
    listen 80;

    # Adiciona header contra MIME sniffing
    add_header X-Content-Type-Options "nosniff" always;

    # Impede que site seja exibido em iframe
    add_header X-Frame-Options "DENY" always;

    # Ativa proteção básica contra XSS
    add_header X-XSS-Protection "1; mode=block" always;

    # Define página personalizada para erro 404
    error_page 404 /error404.html;

    location = /error404.html {
      root /usr/share/nginx/html;
      internal;
    }

    # Define página personalizada para erros 500+
    error_page 500 502 503 504 /error50x.html;

    location = /error50x.html {
      root /usr/share/nginx/html;
      internal;
    }

    location /health {
      add_header Content-Type application/json;
      return 200 '{"status":"ok","component":"nginx"}';
    }

    location /auth/ {

      # Aplica rate limit com burst de 10 requisições
      limit_req zone=api_limit burst=10 nodelay;

      # Ativa cache para esse endpoint
      proxy_cache api_cache;
      
      # Define cache válido por 10 segundos para 200
      proxy_cache_valid 200 10s;
      
      # Ignora headers de controle de cache do backend
      proxy_ignore_headers Cache-Control Expires;
      
      # Ignora cache se houver header Authorization
      proxy_cache_bypass $http_authorization;

      # Não armazena em cache se houver Authorization
      proxy_no_cache $http_authorization;

      # Adiciona header indicando status do cache
      add_header X-Cache-Status $upstream_cache_status;

      # Encaminha requisição para upstream user_service
      proxy_pass http://user_service;

      # Preserva header Host original
      proxy_set_header Host $host;

      # Adiciona IP original na cadeia de proxy
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/voos/ {

      limit_req zone=api_limit burst=10 nodelay;

      proxy_cache api_cache;
      
      proxy_cache_valid 200 10s;
      
      proxy_ignore_headers Cache-Control Expires;
      
      proxy_cache_bypass $http_authorization;
      proxy_no_cache $http_authorization;
      add_header X-Cache-Status $upstream_cache_status;

      rewrite ^/api/voos/(.*)$ /$1 break;

      proxy_pass http://voo_service;

      proxy_set_header Host $host;

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/passagens/ {
      limit_req zone=api_limit burst=10 nodelay;

      # Remove prefixo /api/passagens antes de enviar ao backend
      rewrite ^/api/passagens/(.*)$ /$1 break;

      proxy_pass http://passagem_service;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

  }
}